### ISSUE TITLE
Schema clarification

### ISSUE THREAD

**Issue by pbonte** [rfkd/somfy-control#3]
Hi,

I'm really interested in using your solution, however, as a pure software guy, its a bit unclear where to connect the wires to the remote. 
Would it be possible to further clarify or maybe provide an image that shows where the wires go exactly. 

Thanks in advance. 

Kind regards, 
Pieter

**Comment by rfkd** [comment]
Hi Pieter,

sure, no problem:

![PCB_bottom](https://user-images.githubusercontent.com/8863893/82599812-32abf880-9bad-11ea-9f7f-939ced088a42.jpg)
![PCB_top](https://user-images.githubusercontent.com/8863893/82599817-33dd2580-9bad-11ea-888b-8702fffc90b8.jpg)

The colors are as follows:
| Color | Function |
| --- | --- |
| Red | Vcc (+3V3) |
| Black | Ground |
| White (leftmost) | LED1 |
| Light gray (next to brown) | LED2 |
| Dark gray | LED3 |
| Brown | LED4 |
| Orange | SELECT |
| Yellow | DOWN |
| Purple | MY |
| Blue | UP |

As you can see I integrated the resistors in the wires inside heat shrink tubing.

Hope that helps.

-Ralf
